### ISSUE TITLE
ADD PR Template

### ISSUE THREAD

**Issue by yellowHatpro** [ken1000minus7/YADA#15]
- Add a Pull Request Template

**Comment by HYnam** [comment]
Hi, can I have a try on this?

**Comment by yellowHatpro** [comment]
Hi @HYnam , currently these issues are open for PWoC ( a month long open source event). If you want to contribute in this issue, you can register in the event. Link to the website: https://pwoc.vercel.app

**Comment by HYnam** [comment]
Hi @yellowHatpro I have registered to this event today, but seems the application deadline is over, I'm not sure if this count. I also joined the discord server :)

**Comment by yellowHatpro** [comment]
Hi, thanks for registering. Yeah, the deadlines are over, but contributors can still apply.
