### ISSUE TITLE
JAVA to Kotlin Migration : Options package

### ISSUE THREAD

**Issue by yellowHatpro** [ken1000minus7/YADA#26]
- In this issue, we will be focusing on migrating JAVA code to Kotlin in the options package :
https://github.com/ken1000minus7/YADA/blob/2532095b161fbe73dee1114d821d463b6fd35b62/app/src/main/java/com/kamikaze/yada/options

**Comment by armaanbadhan** [comment]
i would like to work on this

**Comment by yellowHatpro** [comment]
gl 🚀
