### ISSUE TITLE
Fix Memorable Locations "Add a new place" multiple instances creation

### ISSUE THREAD

**Issue by yellowHatpro** [ken1000minus7/YADA#36]
https://user-images.githubusercontent.com/75999921/221530949-81143408-6eef-4e27-aab1-e42576ce8d8a.mp4

Whenever we open the Memorable Location screen, a new instance of Add a new place is created.

**Comment by armaanbadhan** [comment]
pls assign

**Comment by yellowHatpro** [comment]
merged, nice work !!
