### ISSUE TITLE
Avoid Screen from dimming.

### ISSUE THREAD

**Issue by dhruv-porwal** [ken1000minus7/YADA#37]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Issue Type : Adding Features

Please give a brief description of the feature you want to be added

# Expected Behavior
Screen may get dimmed on not under operation by user or from any interruption in a process whenever system not responds for a time.

We need to stop this.
Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Firmware Version:
- Operating System:
- SDK version:
- Toolchain version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by dhruv-porwal** [comment]
Please assign this issue.

**Comment by yellowHatpro** [comment]
@dhruv-porwal can you provide more details of what you want to add through this feature
Maybe provide some screen recording or screenshot for the same

**Comment by yellowHatpro** [comment]
Closing issue due to no feedback
