### ISSUE TITLE
Migrate Code from JAVA to Kotlin in yada package (not subpackages)

### ISSUE THREAD

**Issue by yellowHatpro** [ken1000minus7/YADA#39]
List of files to be migrated:
- FeatureFragment.java
- Feedback.java
- HikersWatchActivity.java
- MainFragmentPagerAdapter.java
- MainPageActivity.java
- MapsActivity.java
- MapsFragment.java
- MemorablePlacesActivity.java
- TranslateActivity.java

**Comment by armaanbadhan** [comment]
pls assign
