### ISSUE TITLE
Restructuring the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [ken1000minus7/YADA#41]
+ I suggest restructuring the Support section to the bottom of the README
+ I would like to be assigned to the issue if approved

**Comment by yellowHatpro** [comment]
@the-amazing-atharva, thanks for showing interest. Since restructuring in itself is not that of an issue, I'd like to know if, apart from it, you can add a contributors' graph.
Also what new additions you can make to make the readme more appealing?

**Comment by the-amazing-atharva** [comment]
Thanks for the reply @yellowHatpro 
+ I can definitely add a contributors image
+ I can add a table of contents
+ I can add suitable emojis to headings
+ If the project has a logo, I can resize it and add it here

Thoughts?

**Comment by the-amazing-atharva** [comment]
Can I work on the issue?

**Comment by yellowHatpro** [comment]
Yeah you can work. I'll be assigning and giving tags a bit later since I'm afk

**Comment by the-amazing-atharva** [comment]
Thanks for the reply
